language: go

os:
  - linux
  - osx

go:
  - 1.8

addons:
  apt:
    packages:
      - socat

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install socat; fi

script:
  make

after_success:
  - bash <(curl -s https://codecov.io/bash)
