language: go

os:
  - linux
  - osx

go:
  - 1.12

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - socat

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install socat; fi

script:
  go test
  go test ./ion

after_success:
  - bash <(curl -s https://codecov.io/bash)
